### PR TITLE
[Feature#45902] [List Book] View List Book in Home

### PR DESCRIPTION
**Pull request by NamBZ**
## Related Tickets:
- [#45902](https://edu-redmine.sun-asterisk.vn/issues/45902)

## WHAT this PR does?
- Add home view
- Add localization (i18n)

## Notes Impacted Areas:
- N/A.

## Attachments:
image

### CODE REVIEW

**Comment by NamBZ** [comment]
ready

**Comment by ghost** [comment]
Fail CI

**Review by ghost — COMMENTED** [review]
Fail CI

**Comment by NamBZ** [comment]
ready

**Review by quyensama — APPROVED** [review]

**Pull request merged**
