### PR TITLE
[Bug#48639] Fix Exception and Test in CartController

### PR DESCRIPTION
**Pull request by NamBZ**
## Related Tickets:
- [#48639](https://edu-redmine.sun-asterisk.vn/issues/48639)

## WHAT this PR does?
Solve problem in Pull Request https://github.com/awesome-academy/php_hn_oe48/pull/36

## Notes Impacted Areas:
- N/A.

## Attachments:
image

### CODE REVIEW

**Comment by NamBZ** [comment]
ready

**Comment by NamBZ** [comment]
comment

**Review by huyenttm-0901 — COMMENTED** [review]
fail CI này em

**Comment by NamBZ** [comment]
ready

Em sửa theo Doc xem CI nó hiển thị test results không mà nó không được

**Review by ghost — COMMENTED** [review]
composer.xml ignore đi nhé

**Comment by NamBZ** [comment]
ready

**Pull request merged**
